export enum RLMTTypes {
  INITIALIZATION_REQUEST = 'app/Main/INITIALIZATION_REQUEST',
  INITIALIZATION_SUCCESS = 'app/Main/INITIALIZATION_SUCCESS',
  INITIALIZATION_FAILURE = 'app/Main/INITIALIZATION_FAILURE',

  CHANGE_SETTINGS = 'app/Main/CHANGE_SETTINGS',

  SELECT_MOD_REQUEST = 'app/Main/SELECT_MOD_REQUEST',
  SELECT_MOD_RESPONSE = 'app/Main/SELECT_MOD_RESPONSE',

  CHECK_MOD = 'app/Main/CHECK_MOD',
  CHECK_ALL_MODS = 'app/Main/CHECK_ALL_MODS',
  CLEAR_CHECKED_MODS = 'app/Main/CLEAR_CHECKED_MODS',

  ACTIVATE_MOD_REQUEST = 'app/Main/ACTIVATE_MOD_REQUEST',
  ACTIVATE_MOD_SUCCESS = 'app/Main/ACTIVATE_MOD_SUCCESS',
  ACTIVATE_MOD_FAILURE = 'app/Main/ACTIVATE_MOD_FAILURE',
}